<a href="https://colab.research.google.com/github/rakshita-vijay/pytorch/blob/main/pt_003_math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.arange(1,5)
tensor_b = torch.arange(5,9)
tensor_a, tensor_b

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]))

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
# if .add_ is used, tensor_a + tensor_b is assigned to tensor_a

In [5]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [6]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [14]:
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])