<a href="https://colab.research.google.com/github/rakshita-vijay/pytorch/blob/main/pt_002_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [8]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch_reshaped = my_torch.reshape(5,2)
my_torch_reshaped

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
my_torch_reshaped = my_torch_reshaped.reshape(2,-1)
my_torch_reshaped

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch_reshaped = my_torch_reshaped.reshape(-1,2)
my_torch_reshaped

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
my_torch_flat = my_torch_reshaped.view(-1)
print(my_torch_flat)
print(my_torch_reshaped)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [20]:
my_torch_reshaped

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
my_torch_flat[1] = 666333
my_torch_reshaped

tensor([[     0, 666333],
        [     2,      3],
        [     4,      5],
        [     6,      7],
        [     8,      9]])

In [26]:
my_torch_reshaped[2] = 420
my_torch_flat
my_torch_reshaped

tensor([[     0, 666333],
        [     2,      3],
        [   420,    420],
        [     6,      7],
        [     8,      9]])

In [28]:
torch_slice = torch.arange(10)
torch_slice_reshaped = torch_slice.reshape(5,2)
torch_slice_reshaped

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [31]:
torch_slice_reshaped[:,1]

tensor([1, 3, 5, 7, 9])