<a href="https://colab.research.google.com/github/rakshita-vijay/pytorch/blob/main/pt_001_tensor_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip list

In [4]:
import torch
import numpy as np

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.03403167, 0.51282728, 0.21179868, 0.92949395],
       [0.02955147, 0.12029222, 0.23377929, 0.17012939],
       [0.13328354, 0.49627703, 0.42336854, 0.10626969]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
tensor_2darr = torch.randn(3,4)
tensor_2darr

tensor([[-0.2125,  0.2350, -0.5598, -0.2579],
        [ 0.4142,  1.7947,  0.7132, -1.2504],
        [-0.2695, -1.7111, -0.9820, -0.0655]])

In [8]:
tensor_2darr.dtype

torch.float32

In [12]:
tensor_3darr = torch.zeros(3,4,5)
tensor_3darr

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [13]:
# create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0340, 0.5128, 0.2118, 0.9295],
        [0.0296, 0.1203, 0.2338, 0.1701],
        [0.1333, 0.4963, 0.4234, 0.1063]], dtype=torch.float64)